# Generated by Django 4.2.1 on 2023-05-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necrotopia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
