# Generated by Django 4.2.1 on 2023-06-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necrotopia', '0004_moduleassembly_modulegrade_modulegradesubassembly_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleassembly',
            old_name='active',
            new_name='published',
        ),
    ]
