# Generated by Django 4.2.1 on 2023-06-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necrotopia', '0005_rename_active_moduleassembly_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleassembly',
            options={'verbose_name': 'Blueprint', 'verbose_name_plural': 'Blueprints'},
        ),
        migrations.RemoveField(
            model_name='itempicture',
            name='assembly_item',
        ),
        migrations.AddField(
            model_name='itempicture',
            name='imd_assembly_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='img_picture_ModuleAssembly', to='necrotopia.moduleassembly'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('pdf_assembly_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_picture_ModuleAssembly', to='necrotopia.moduleassembly')),
            ],
        ),
    ]
