# Generated by Django 4.2.1 on 2023-06-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necrotopia', '0010_financialinstitution_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstitution',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
